[package]
name = "lucastra-input"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
tracing = { workspace = true }
lucastra-core = { path = "../core" }
lucastra-hal = { path = "../hal" }
