[package]
name = "lucastra-search"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
lucastra-core = { path = "../core" }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
