[package]
name = "lucastra-compat"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = []
relibc = []

[dependencies]
lucastra-core = { path = "../core" }
tracing = { workspace = true }
thiserror = { workspace = true }
