[package]
name = "lucastra-kernel"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = []
relibc = ["dep:lucastra-compat"]

[dependencies]
tracing = { workspace = true }
lucastra-compat = { path = "../compat", optional = true }
