[package]
name = "lucastra-config"
version = "1.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
toml = "0.8"
dirs = "5.0"
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
